### ISSUE TITLE
Cannot load .jar

### ISSUE THREAD

**Issue by mfurlend** [mollie/PhpStorm#1]
PHPStorm 9.5 cannot load the .jar file. The error message is "Failed to load plugin descriptor from file Mollie--PhpStorm.jar." However, I did manage to get PHPStorm to load the plugin by extracting the jar file (`jar -xf Mollie-PhpStorm.jar`) and compressing the contents into a `.zip` file.

**Comment by mollierobbert** [comment]
Thanks for notifying us Mikhail. We've recompiled the .jar file - should be good now.
